global:
  tlsDisable: true

server:
  image:
#    tag: "1.19.5-ent"
    repository: hashicorp/vault-enterprise
  affinity: ""
  enterpriseLicense:
    secretName: vault-license
    # storageClass is set dynamically based on platform during helm install
    # dataStorage:
    #  enabled: true
    # EKS: gp2, GKE: cluster default, Minikube: standard

injector:
  enabled: "false"

csi:
  enabled: true